language: node_js

# Earlier versions of node should work, but they can't run the tests due to async functions, etc.
node_js:
  - "lts/*"
  - "node"
  - "8"
  - "7"

script:
  - npm run lint
  - npm test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
