language: node_js

# Earlier versions of node should work, but they can't run the tests due to async functions, etc.
node_js:
  - "7"
  - "8"
  - "node"
  - "lts/*"
  
after_success:
  - 'cat ./coverage/lcov.info ./node_modules/.bin/coveralls'
