language: node_js

# Earlier versions of node should work, but they can't run the tests due to async functions, etc.
node_js:
  - "7"
  - "8"
  - "node"
  - "lts/*"

script:
  - npm run lint
  - npm test

after_success:
  - npm run coveralls
